// <auto-generated />
using System;
using CenterFieldCoffee.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CenterFieldCoffee.Migrations
{
    [DbContext(typeof(CenterFieldCoffeeContext))]
    partial class CenterFieldCoffeeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("CenterFieldCoffee.Models.Store", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<short>("closing_hour")
                        .HasColumnType("INTEGER");

                    b.Property<short>("closing_minute")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("create_date")
                        .HasColumnType("TEXT");

                    b.Property<short>("opening_hour")
                        .HasColumnType("INTEGER");

                    b.Property<short>("opening_minute")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("update_date")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Store");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a64181fd-fc94-4189-9dc1-e7f891106470"),
                            Name = "Store 1",
                            closing_hour = (short)18,
                            closing_minute = (short)0,
                            create_date = new DateTime(2024, 8, 10, 3, 53, 33, 32, DateTimeKind.Utc).AddTicks(3365),
                            opening_hour = (short)6,
                            opening_minute = (short)30
                        },
                        new
                        {
                            Id = new Guid("9b55a5ab-44f5-4e4e-96cf-a2e9e81a2c08"),
                            Name = "Store 2",
                            closing_hour = (short)21,
                            closing_minute = (short)0,
                            create_date = new DateTime(2024, 8, 10, 3, 53, 33, 32, DateTimeKind.Utc).AddTicks(3379),
                            opening_hour = (short)6,
                            opening_minute = (short)30
                        },
                        new
                        {
                            Id = new Guid("f8c94d04-f86f-4f88-822a-84bdfd197055"),
                            Name = "Store 4",
                            closing_hour = (short)20,
                            closing_minute = (short)0,
                            create_date = new DateTime(2024, 8, 10, 3, 53, 33, 32, DateTimeKind.Utc).AddTicks(3386),
                            opening_hour = (short)16,
                            opening_minute = (short)30
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
